server:
  port: 9003
  forward-headers-strategy: framework

spring:
  config:
    import: optional:classpath:common-observability.yml
  application:
    name: interaction-service

  data:
    mongodb:
      uri: ${MONGODB_URI:mongodb://localhost:27019/interaction_db?maxPoolSize=50&minPoolSize=10&maxIdleTimeMS=300000&waitQueueTimeoutMS=10000}

  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: ${KEYCLOAK_ISSUER_URI:http://localhost:8443/realms/elearning-realm}
          jwk-set-uri: ${KEYCLOAK_JWKS_URI:http://localhost:8443/realms/elearning-realm/protocol/openid-connect/certs}

eureka:
  instance:
    prefer-ip-address: true
    instance-id: ${spring.application.name}:${spring.application.instance_id:${random.value}}
  client:
    service-url:
      defaultZone: ${EUREKA_SERVER:http://localhost:8761/eureka/}
    register-with-eureka: true
    fetch-registry: true

logging:
  level:
    root: INFO
    com.hust.interactionservice: DEBUG
    org.springframework.data.mongodb.core.MongoTemplate: DEBUG
    org.springframework.security: INFO

