server:
  port: 9002

spring:
  application:
    name: media-service
  
  data:
    mongodb:
      uri: ${MONGODB_URI:mongodb://localhost:27020/e_learning_media}
  
  # Security (OAuth2 Keycloak) - Thêm để đồng bộ
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: ${KEYCLOAK_ISSUER_URI:http://localhost:8443/realms/elearning-realm}
          jwk-set-uri: ${KEYCLOAK_JWKS_URI:http://localhost:8443/realms/elearning-realm/protocol/openid-connect/certs}

  servlet:
    multipart:
      max-file-size: 100MB
      max-request-size: 100MB

eureka:
  client:
    service-url:
      defaultZone: ${EUREKA_SERVER:http://localhost:8761/eureka/}
  instance:
    prefer-ip-address: true
    instance-id: ${spring.application.name}:${spring.application.instance_id:${random.value}}

app:
  storage:
    provider: LOCAL # LOCAL, CLOUDINARY, S3
    local:
      path: ./uploads
      base-url: http://localhost:8086/files/
  
  cloudinary:
    cloud-name: ${CLOUDINARY_CLOUD_NAME:}
    api-key: ${CLOUDINARY_API_KEY:}
    api-secret: ${CLOUDINARY_API_SECRET:}

logging:
  level:
    root: INFO
    com.hust.mediaservice: DEBUG
