server:
  port: 9004

spring:
  application:
    name: order-service
  datasource:
    url: ${JDBC_DATABASE_URL:jdbc:postgresql://localhost:5433/e_learning_order}
    username: ${JDBC_DATABASE_USERNAME:postgres}
    password: ${JDBC_DATABASE_PASSWORD:}
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.PostgreSQLDialect

eureka:
  instance:
    prefer-ip-address: true
    instance-id: ${spring.application.name}:${spring.application.instance_id:${random.value}}
  client:
    service-url:
      defaultZone: ${EUREKA_SERVER:http://localhost:8761/eureka/}
    register-with-eureka: true
    fetch-registry: true

logging:
  level:
    root: INFO
    com.hust.orderservice: DEBUG
    org.hibernate.SQL: DEBUG

payment:
  vnpay:
    tmn-code: B0G7MQOH
    hash-secret: MUQDZO18PYW9GLBHMISDS442I9SARIHT
    url: https://sandbox.vnpayment.vn/paymentv2/vpcpay.html
    return-url: http://localhost:3000/order/vnpay-return
