version: "3.8"

services:
  # Database for Course Service
  elearning-mongodb:
    image: mongo:latest
    container_name: elearning-mongodb
    environment:
      MONGO_INITDB_DATABASE: course_db
    ports:
      - "27017:27017"
    volumes:
      - course_mongo_data:/data/db

volumes:
  course_mongo_data:

networks:
  default:
    name: elearning-network
    external: true
