
services:
  elearning-media-db:
    image: mongo:latest
    container_name: elearning-media-db
    environment:
      MONGO_INITDB_DATABASE: media_db
    ports:
      - "27020:27017" # Sử dụng 27020 để không trùng với các service khác
    volumes:
      - media_mongo_data:/data/db
    healthcheck:
      test: ["CMD", "mongosh", "--eval", "db.adminCommand('ping')"]
      interval: 5s
      timeout: 5s
      retries: 5

  minio:
    image: minio/minio:latest
    container_name: minio
    ports:
      - "9100:9000"
      - "9101:9001"
    environment:
      MINIO_ROOT_USER: minioadmin
      MINIO_ROOT_PASSWORD: minioadmin
      MINIO_API_CORS_ALLOW_ORIGIN: "*"
    volumes:
      - minio_data:/data
    command: server /data --console-address ":9001"

volumes:
  media_mongo_data:
  minio_data:

networks:
  default:
    name: elearning-network
    external: true
